schema: "classroom50/repo-config/v1"
classroom: "herramientas-26"
assignment: "introduccion-a-git"
owner:
  username: "lolapinkbit"
  id: 178744519
  accepted_at: "2026-09-06T23:03:12Z"
source:
  owner: "TDHclassroom"
  owner_id: 219900396
  repo: "git-basic"
  branch: "main"
